version: '3'
services:
  postgres:
    image: postgres:13
    volumes:
      - /home/vol/psql:/var/libpostgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: x5
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080